=== shritej1808/AssignmentWeb/mentorship_application.dtd
<!ELEMENT mentorship_application (name, usn, year, parent_name, mobile, hobbies, semester, email, gender)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT usn (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT parent_name (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT hobbies (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT gender (#PCDATA)>

=== shritej1808/AssignmentWeb/mentorship_application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mentorship_application SYSTEM "mentorship_application.dtd">
<mentorship_application>
    <name></name>
    <usn></usn>
    <year></year>
    <parent_name></parent_name>
    <mobile></mobile>
    <hobbies></hobbies>
    <semester></semester>
    <email></email>
    <gender></gender>
</mentorship_application>
